name: 📢 publish

on:
  push:
    tags:
      - '[0-9]+.[0-9]+.[0-9]+*'

env:
  NODE_VERSION: 20.9.0

jobs:
  publish:
    name: 📢 Publish
    permissions:
      packages: write
      contents: read
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@08c6903cd8c0fde910a37f88322edcfb5dd907a8 # v5.0.0
      - uses: actions/setup-node@49933ea5288caeca8642d1e84afbd3f7d6820020 # v4.4.0
        with:
          node-version: ${{ env.NODE_VERSION }}
          registry-url: https://registry.npmjs.org/
      # Skip post-install scripts here, as a malicious
      # script could steal NODE_AUTH_TOKEN.
      - name: Install dependencies
        run: yarn install --frozen-lockfile
        env:
          CI: true
          NODE_AUTH_TOKEN: ${{ secrets.CI_NPM_READ_ORG }}

      - name: Publish to NPM Package Registry
        run: npm publish --access=public
        env:
          CI: true
          NODE_AUTH_TOKEN: ${{ secrets.CI_NPM_REGISTRY }}
