name: 📢 publish

on:
  push:
    tags:
      - '[0-9]+.[0-9]+.[0-9]+*'

env:
  NODE_VERSION: 16.14

jobs:
  publish:
    name: 📢 Publish
    permissions:
      packages: write
      contents: read
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@11bd71901bbe5b1630ceea73d27597364c9af683 # v4.2.2
      - uses: actions/setup-node@39370e3970a6d050c480ffad4ff0ed4d3fdee5af # v4.1.0
        with:
          node-version: ${{ env.NODE_VERSION }}
          registry-url: https://registry.npmjs.org/
      # Skip post-install scripts here, as a malicious
      # script could steal NODE_AUTH_TOKEN.
      - name: Install dependencies
        run: yarn install --frozen-lockfile
        env:
          CI: true
          NODE_AUTH_TOKEN: ${{ secrets.CI_NPM_READ_ORG }}

      - name: Publish to NPM Package Registry
        run: npm publish --access=public
        env:
          CI: true
          NODE_AUTH_TOKEN: ${{ secrets.CI_NPM_REGISTRY }}
